name: C/C++ CI

on:
  push:
    branches: 
      - branchMake


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      
      - name: set up gcc
        run: sudo apt-get install g++ 
      
      - name: build 
        run: make
        
      - name: run tests in any
        run: ./class
