name: Tests

on: 
  push:
    branches: ["brachAutoTest"]
  pull_request: 
    branches: ["brachAutoTest"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev autoconf automake libtool

      - name: Update autotools
        run: |
          autoconf --version
          automake --version
          libtool --version

      - name: Generate configure script
        run: |
          autoreconf --install --force --verbose

      - name: Configure project
        run: |
          ./configure --disable-dependency-tracking || { echo "Configure failed"; exit 1; }

      - name: Build
        run: |
          make || { echo "Build failed"; exit 1; }

      - name: Run Tests
        run: |
          make check || { echo "Tests failed"; exit 1; }

      - name: Show config.log on failure
        if: failure()
        run: |
          echo "------ BEGIN config.log ------"
          cat config.log || echo "config.log not found"
          echo "------ END config.log ------"
