name: Tests

on: 
  push:
    branches: ["brachAutoTest"]
  pull_request: 
    branches: ["brachAutoTest"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgtest-dev automake autoconf
          sudo apt-get install -y gmake
          sudo ln -s /usr/bin/make /usr/bin/gmake

      - name: Generate configure script
        run: |
          autoreconf --install --force --verbose

      - name: Configure project
        run: |
          ./configure --disable-dependency-tracking

      - name: Build
        run: |
          make

      - name: Run Tests
        run: |
          make check || { echo "Tests failed"; exit 1; }

      - name: Display config.log if configure fails
        if: failure()
        run: |
          if [ -f config.log ]; then
            echo "------ BEGIN config.log ------"
            cat config.log
            echo "------ END config.log ------"
          else
            echo "config.log not found"
          fi
